name: GitHub Trophy

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: askvs
          output_path: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Trophy
        uses: EndBug/add-and-commit@v9
        with:
          add: "trophy.svg"
          message: "Update GitHub trophies"
