name: Generate GitHub Trophy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write

jobs:
  trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: askvs
          file: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: tokyonight
          max-cols: 6
          max-rows: 2

      - name: Commit trophy
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update GitHub trophies"
          file_pattern: trophy.svg
